### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by JingYinji** [clearloveu/LEO_Mobility_NS-3#1]
您好，感谢您的分享。使用ns3.28和ns3.33在编译的时候都出现了。期待您的回复
../src/mobility/model/leo-satellite-helper.cc: In member function ‘void ns3::LEOSatelliteHelper::handle() const’:
../src/mobility/model/leo-satellite-helper.cc:286:11: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘SetCacheDirty’; did you mean ‘g_isCacheDirty’?
       rp->SetCacheDirty(true);
           ^~~~~~~~~~~~~
           g_isCacheDirty
../src/mobility/model/leo-satellite-helper.cc: In member function ‘bool ns3::LEOSatelliteHelper::isLinkInterruption(ns3::Ptr<ns3::Node>) const’:
../src/mobility/model/leo-satellite-helper.cc:506:6: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘SetCacheDirty’; did you mean ‘g_isCacheDirty’?
  rp->SetCacheDirty(true);
      ^~~~~~~~~~~~~
      g_isCacheDirty
../src/mobility/model/leo-satellite-helper.cc:507:38: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘GetShortPath’
  std::vector< Ptr<Node> > path = rp->GetShortPath(source, dest);//在当前快照下得到当前卫星发送的分组所经过的卫星
                                      ^~~~~~~~~~~~
../src/mobility/model/leo-satellite-helper.cc: In member function ‘ns3::Ptr<ns3::Node> ns3::LEOSatelliteHelper::findFirstNodeOutOfPolarRegionByDoubleV(ns3::Ptr<ns3::Node>, ns3::Ptr<ns3::Node>) const’:
../src/mobility/model/leo-satellite-helper.cc:610:39: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘GetShortPath’
  std::vector< Ptr<Node> > path1 = rp->GetShortPath(upNodeOutOfPR, dest);
                                       ^~~~~~~~~~~~
../src/mobility/model/leo-satellite-helper.cc:611:39: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘GetShortPath’
  std::vector< Ptr<Node> > path2 = rp->GetShortPath(downNodeOutOfPR, dest);
                                       ^~~~~~~~~~~~
../src/mobility/model/leo-satellite-helper.cc: In member function ‘std::vector<ns3::Ptr<ns3::Node> > ns3::LEOSatelliteHelper::findPathFromNix(ns3::Ptr<ns3::Node>)’:
../src/mobility/model/leo-satellite-helper.cc:1143:44: error: ‘class ns3::Ipv4NixVectorRouting’ has no member named ‘GetShortPath’
   std::vector< Ptr<Node> > path_temp = rp->GetShortPath(from, to);

**Comment by clearloveu** [comment]
不好意思，这么晚回复您。
根据您的报错情况，应该是没有将src/nix-vector-routing代替，readme已更新。

**Comment by JingYinji** [comment]
> 不好意思，这么晚回复您。
> 根据您的报错情况，应该是没有将src/nix-vector-routing代替，readme已更新。

谢谢您，我马上试一试

**Comment by JingYinji** [comment]
> > 不好意思，这么晚回复您。
> > 根据您的报错情况，应该是没有将src/nix-vector-routing代替，readme已更新。
> 
> 谢谢您，我马上试一试

../src/buildings/model/building.cc: In member function ‘bool ns3::Building::IsIntersect(const Vector&, const Vector&) const’:
../src/buildings/model/building.cc:290:27: error: ‘const class ns3::Box’ has no member named ‘IsIntersect’
   return m_buildingBounds.IsIntersect (l1, l2);
                           ^~~~~~~~~~~
实在不好意思，又打扰您，按照更新的操作又出现了如下报错。我用的是ns-3.33，请问这个问题是版本不一致导致的吗，想请问一下您，您现在在您自己的3.29上还是可以编译吗？

**Comment by clearloveu** [comment]
3.29可以编译
编译的时候不要添加其他参数，只需要./waf configure 和./waf build




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [clearloveu/LEO_Mobility_NS-3] 编译失败 (#1)





   
不好意思，这么晚回复您。
 根据您的报错情况，应该是没有将src/nix-vector-routing代替，readme已更新。
  
谢谢您，我马上试一试
  
../src/buildings/model/building.cc: In member function ‘bool ns3::Building::IsIntersect(const Vector&amp;, const Vector&amp;) const’:
 ../src/buildings/model/building.cc:290:27: error: ‘const class ns3::Box’ has no member named ‘IsIntersect’
 return m_buildingBounds.IsIntersect (l1, l2);
 ^~~~~~~~~~~
 实在不好意思，又打扰您，按照更新的操作又出现了如下报错。我用的是ns-3.33，请问这个问题是版本不一致导致的吗，想请问一下您，您现在在您自己的3.29上还是可以编译吗？

**Comment by JingYinji** [comment]
[1882/1968] Compiling build/src/propagation/bindings/ns3module.cc
In file included from src/nix-vector-routing/bindings/ns3module.cc:1:0:
src/nix-vector-routing/bindings/ns3module.h:1081:10: error: ‘SocketAddressTag’ in namespace ‘ns3’ does not name a type
     ns3::SocketAddressTag *obj;
          ^~~~~~~~~~~~~~~~

您好，很抱歉一直打扰您，又用了一下ns3.29编译出现了以下问题。特别感谢您的耐心解答

**Comment by upc1702lx** [comment]
> [1882/1968] Compiling build/src/propagation/bindings/ns3module.cc In file included from src/nix-vector-routing/bindings/ns3module.cc:1:0: src/nix-vector-routing/bindings/ns3module.h:1081:10: error: ‘SocketAddressTag’ in namespace ‘ns3’ does not name a type ns3::SocketAddressTag *obj; ^~~~~~~~~~~~~~~~
> 
> 您好，很抱歉一直打扰您，又用了一下ns3.29编译出现了以下问题。特别感谢您的耐心解答

请问这个问题您解决了吗，我编译过程中同样出现这个 error: ‘SocketAddressTag’ in namespace ‘ns3’ does not name a type
ns3::SocketAddressTag *obj;

**Comment by xieflynext** [comment]
我也在编译后出现了相同的问题 请问这个问题解决了吗  能否提供一些参考建议

**Comment by clearloveu** [comment]
当时应该用的是ns27版本，加上调整了什么参数，具体忘记了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月28日 03:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [clearloveu/LEO_Mobility_NS-3] 编译失败 (#1) |

请问这个问题解决了吗 能否提供一些参考建议

**Comment by xieflynext** [comment]
我在测试的时候3.29也是可以编译的，实测是绑定python接头方面出现问题了。可以删除绑定python的代码即可编译成功
