### ISSUE TITLE
Are there any related papers published based on this project?

### ISSUE THREAD

**Issue by uestcxt** [clearloveu/LEO_Mobility_NS-3#2]

**Comment by clearloveu** [comment]
只有学术论文，相关链接：https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD202201&filename=1021854173.nh&uniplatform=NZKPT&v=X21TNBLNKGurqa8SGy5ypp-lL7xdUbi1QJfMAJo0mvgFcI4t9fN3LpzXjLpHqmtx
