### ISSUE TITLE
Request Documentation Support

### ISSUE THREAD

**Issue by jingjiuxiaoshishu** [clearloveu/LEO_Mobility_NS-3#3]
Is there a link to your master's thesis? thank you very much!

**Comment by clearloveu** [comment]
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD202201&filename=1021854173.nh&uniplatform=NZKPT&v=X21TNBLNKGurqa8SGy5ypp-lL7xdUbi1QJfMAJo0mvgFcI4t9fN3LpzXjLpHqmtx

**Comment by jingjiuxiaoshishu** [comment]
根據readme，您的項目使用的ns版本為3.29，但項目中使用的SocketAddressTag在ns3.25到ns3.26版本時已經刪除了……是否使用版本記錯了？
